"""Stable tool identities independent of a widget implementation."""
from enum import Enum

class ToolKind(Enum):
    OBJECT_SELECT = "object_select"
    RASTER_PENCIL = "raster_pencil"
    BRUSH = "brush"
    LASSO_BRUSH = "lasso_brush"
    RASTER_ERASER = "raster_eraser"
    EYEDROPPER = "eyedropper"
    FILL = "fill"
    GRADIENT = "gradient"
    MASK_SELECT = "mask_select"
    MASK_WAND = "mask_wand"
    TEXT_EDIT = "text_edit"
    TRANSFORM = "transform"
    CAGE_TRANSFORM = "cage_transform"
    SHAPE_EDIT = "shape_edit"
    BOUND_EDIT = "shape_edit"
    VECTOR_EDIT = "vector_edit"
    VECTOR_REDRAW = "vector_redraw"
    VECTOR_CONNECT = "vector_connect"
    VECTOR_SIMPLIFY = "vector_simplify"
    DRAW_SELECT_RECT = "draw_select_rect"
    DRAW_SELECT_LASSO = "draw_select_lasso"
    DRAW_SELECT_STROKE = "draw_select_stroke"
    DRAW_SHAPE = "draw_shape"
    INSERT_PAGE_GAP = "insert_page_gap"
    BOX_BOUND = "box_bound"
    CIRCLE_BOUND = "circle_bound"
    SHAPE_CREATE = "shape_create"
    POLYGON_BOUND = "shape_create"
    RASTER_CREATE = "raster_create"
